apiVersion: apps/v1
kind: Deployment
metadata:
  name: spark
spec:
  selector:
    matchLabels:
      app: spark
  template:
    metadata:
      labels:
        app: spark
    spec:
      containers:
      - name: spark
        image: huaiyugong/spark-gpu:v1
